site_name: Coffee, Beer and DevOps
site_author: Ricardo Verhaeg
site_description: Some thoughts on coffee, beers and DevOps!
site_url: https://rverhaeg.com
site_dir: rverhaeg.com

copyright: 'Copyright &copy; Ricardo Verhaeg'

# Repository
repo_name: 'Verhaeg/rverhaeg'
repo_url: 'https://github.com/Verhaeg/rverhaeg'

theme: material

pages:
  - Home: index.md
  - Coffee:
    - Blends: coffee/blends.md
  - Beer:
    - Top: beer/top.md
  - DevOps:
    - Tools: devops/tools.md
    - Issues: devops/issues.md
  - About: about.md

markdown_extensions:
  - codehilite
  - smarty
  - sane_lists
  - footnotes
  # - toc:
  #   permalink: True

extra:
  palette:
    primary: blue grey
    accent: orange
  # logo: img/logo.svg
  social:
    - type: github
      link: https://github.com/Verhaeg
    - type: twitter
      link: https://twitter.com/Holandes
    - type: linkedin
      link: https://linkedin.com/in/rverhaeg
